services:
  app:
    build: .
    image: research-app:v1
    container_name: springboot-app

    ports:
      - "8080:8080"
    environment:

        - SPRING_DATASOURCE_URL=${DB_URL}
        - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
        - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
        - SPRING_JPA_HIBERNATE_DDL-AUTO=update
        - SPRING_JPA_SHOW_SQL=true
        - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
        - ADMIN_NAME=${ADMIN_NAME}
        - ADMIN_EMAIL=${ADMIN_EMAIL}
        - ADMIN_PASSWORD=${ADMIN_PASSWORD}

        - SPRING_DATA_REDIS_HOST=${SPRING_DATA_REDIS_HOST}
        - SPRING_DATA_REDIS_PORT=${REDIS_PORT}
        - JWT_SECRET=${SECRET_KEY}
        - SPRING_SENDGRID_API_KEY=${SENDGRID_API_KEY}
        - SPRING_SENDGRID_PROXY_HOST=${SENDGRID_PROXY_HOST}

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy
    volumes:
      - ./src:/app/src

    restart: always


  postgres:
    image: postgres:16
    container_name: postgres-db

    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  minio:
    image: minio/minio
    container_name: minio_storage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: always

    env_file:
      - .env

volumes:
  redis_data:
  minio_data:
  postgres_data: