services:
  app:
    build: .
    image: research-app:v1
    container_name: springboot-app

    ports:
      - "8080:8080"
    environment:

        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
        - SPRING_DATASOURCE_USERNAME=${DB_USER}
        - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
        - SPRING_JPA_HIBERNATE_DDL-AUTO=update
        - SPRING_JPA_SHOW-SQL=true
        - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true

        - SPRING_DATA_REDIS_HOST=redis
        - SPRING_DATA_REDIS_PORT=${REDIS_PORT}

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy

    volumes:
      - ./src:/app/src
    restart: always


  postgres:
    image: postgres:16
    container_name: postgres-db

    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: always

volumes:
  postgres_data:
  redis_data:


