name: Deploy to EC2 Server

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22

          timeout: 30m
          command_timeout: 30m

          script: |

            echo "========== CONNECTED TO EC2 =========="

            cd ~/research-paper-system-springboot

            echo "========== CURRENT DIRECTORY =========="
            pwd

            echo "========== CURRENT FILES =========="
            ls

            echo "========== GIT STATUS =========="
            git status

            echo "========== PULLING LATEST CODE =========="
            git pull origin main

            echo "========== CURRENT BRANCH =========="
            git branch

            echo "========== DOCKER VERSION =========="
            sudo docker --version

            echo "========== DOCKER COMPOSE VERSION =========="
            sudo docker compose version

            echo "========== STOPPING OLD CONTAINERS =========="
            sudo docker compose -f docker-compose.prod.yml down

            echo "========== REMOVING UNUSED CONTAINERS =========="
            sudo docker container prune -f

            echo "========== BUILDING NEW IMAGE =========="
            sudo docker compose -f docker-compose.prod.yml build --progress=plain

            echo "========== STARTING NEW CONTAINERS =========="
            sudo docker compose -f docker-compose.prod.yml up -d

            echo "========== RUNNING CONTAINERS =========="
            sudo docker ps -a

            echo "========== DOCKER NETWORKS =========="
            sudo docker network ls

            echo "========== SPRING BOOT CONTAINER LOGS =========="
            sudo docker logs springboot-app --tail=200

            echo "========== NGINX CONTAINER LOGS =========="
            sudo docker logs nginx-reverse-proxy --tail=100

            echo "========== CONTAINER RESOURCE USAGE =========="
            sudo docker stats --no-stream

            echo "========== CLEANING UNUSED IMAGES =========="
            sudo docker image prune -f

            echo "========== DEPLOYMENT FINISHED =========="














#name: Spring Boot CI/CD
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#
#  build-and-push:
#
#    runs-on: ubuntu-latest
#
#    steps:
#
#      # Checkout Repository
#      - name: Checkout Repository
#        uses: actions/checkout@v6
#
#
#      # Setup Java
#      - name: Setup Java 17
#        uses: actions/setup-java@v4
#        with:
#          distribution: temurin
#          java-version: 17
#
#
#      # Build Spring Boot Project
#      - name: Build with Maven
#        run: mvn clean package -DskipTests
#
#
#      # Login to Docker Hub
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#
#      # Build Docker Image
#      - name: Build Docker Image
#        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/research-app:v1 .
#
#      # Push Docker Image
#      - name: Push Docker Image
#        run: docker push ${{ secrets.DOCKER_USERNAME }}/research-app:v1







