name: Deploy to EC2 Server

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
     
      - name: Deploy to EC2 Server
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22

          script: |

            echo "==============================="
            echo "CONNECTED TO EC2 SERVER"
            echo "==============================="

            cd ~/research-paper-system-springboot

            echo "==============================="
            echo "PULLING LATEST GITHUB CODE"
            echo "==============================="

            git pull origin main
            
            echo "==============================="
            echo "CLEANUP UNUSED IMAGES"
            echo "==============================="

            sudo docker image prune -f
            
            
            echo "==============================="
            echo "STOPPING OLD CONTAINERS"
            echo "==============================="

            sudo docker compose -f docker-compose.prod.yml down

            echo "==============================="
            echo "PULLING LATEST DOCKER IMAGE"
            echo "==============================="

            sudo docker pull zohaibsaraj/research-app:latest

            echo "==============================="
            echo "STARTING CONTAINERS"
            echo "==============================="

            sudo docker compose -f docker-compose.prod.yml up -d

            echo "==============================="
            echo "RUNNING CONTAINERS"
            echo "==============================="

            sudo docker ps

            echo "==============================="
            echo "DOCKER LOGS"
            echo "==============================="

            sudo docker logs springboot-app --tail 50

            echo "==============================="
            echo "DEPLOYMENT FINISHED"
            echo "==============================="